/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303032",
        "inverse-primary": "#ffb3b1",
        "surface-container-high": "#eae7ea",
        "tertiary-fixed": "#ffe16d",
        "tertiary": "#705d00",
        "on-secondary-container": "#783d01",
        "surface-tint": "#bb152c",
        "inverse-on-surface": "#f3f0f2",
        "on-primary-fixed": "#410007",
        "on-tertiary-container": "#4c3f00",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#2f1400",
        "on-background": "#1b1b1d",
        "surface-bright": "#fcf8fb",
        "outline": "#8f6f6e",
        "on-tertiary-fixed-variant": "#544600",
        "on-surface-variant": "#5b403f",
        "primary-container": "#db313f",
        "primary-fixed": "#ffdad8",
        "tertiary-container": "#c9a900",
        "on-surface": "#1b1b1d",
        "secondary": "#8e4e14",
        "outline-variant": "#e4bebc",
        "surface-dim": "#dcd9dc",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2e4",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-fixed-variant": "#92001c",
        "on-tertiary-fixed": "#221b00",
        "background": "#fcf8fb",
        "primary": "#b7102a",
        "surface-variant": "#e4e2e4",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f5",
        "secondary-container": "#ffab69",
        "secondary-fixed-dim": "#ffb780",
        "surface-container": "#f0edef",
        "on-secondary-fixed-variant": "#6f3800",
        "tertiary-fixed-dim": "#e9c400",
        "secondary-fixed": "#ffdcc4",
        "on-primary": "#ffffff",
        "surface": "#fcf8fb",
        "surface-container-lowest": "#ffffff",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
